name: build

on: [push, pull_request, workflow_dispatch]

env:
  NAME: AutoItX.Dotnet.Latest
  CONFIG: NuGet
  BIN_POSTFIX: .Bin
  RETENTION_DAYS: 1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    # Check out

    - name: Check out ${{env.NAME}}
      uses: actions/checkout@v4.2.2

    # Build

    - name: Build ${{env.NAME}} ${{env.CONFIG}}
      run: dotnet build ${{env.NAME}}.sln --configuration ${{env.CONFIG}}

    # Upload artifacts

    - name: Publish ${{env.NAME}} ${{env.CONFIG}}
      uses: actions/upload-artifact@v4.6.0
      with:
        name: ${{env.NAME}}${{env.BIN_POSTFIX}}
        path: ${{env.NAME}}/bin/${{env.CONFIG}}/${{env.NAME}}.*.*nupkg
        retention-days: ${{env.RETENTION_DAYS}}
